# Generated by Django 2.1.8 on 2019-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favcolor',
        ),
    ]
