# Generated by Django 2.1.8 on 2019-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190409_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Data Clerk'), (2, 'Prescriber'), (3, 'Health Official'), (4, 'Admin')], default='0'),
        ),
    ]
